version: '3.8'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    mem_limit: 1400m
    ports:
      - "38086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=edge
      - DOCKER_INFLUXDB_INIT_PASSWORD=edgeadmin
      - DOCKER_INFLUXDB_INIT_ORG=CTC
      - DOCKER_INFLUXDB_INIT_BUCKET=UR10e
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=testtoken
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "2"
    # networks:
    #   proxy-redirect:
    #     aliases:
    #       - influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=edge
      - GF_SECURITY_ADMIN_PASSWORD=edge
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  influxdb_data:
  grafana_data:
