{
 "title": "Universal Robots 10e Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "TCP Velocity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "query": "from(bucket: \"UR10e\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TCP_velocity_X\" or r[\"_measurement\"] == \"TCP_velocity_Y\" or r[\"_measurement\"] == \"TCP_velocity_Z\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "TCP Position",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"UR10e\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TCP_Position_X\" or r[\"_measurement\"] == \"TCP_Position_Y\" or r[\"_measurement\"] == \"TCP_Position_Z\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Joints Velocity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rotrads" } },
   "targets": [
    {
     "query": "from(bucket: \"UR10e\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Joints_velocity_0\" or r[\"_measurement\"] == \"Joints_velocity_1\" or r[\"_measurement\"] == \"Joints_velocity_2\" or r[\"_measurement\"] == \"Joints_velocity_3\" or r[\"_measurement\"] == \"Joints_velocity_4\" or r[\"_measurement\"] == \"Joints_velocity_5\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Joints Position",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"UR10e\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Joints_position_0\" or r[\"_measurement\"] == \"Joints_position_1\" or r[\"_measurement\"] == \"Joints_position_2\" or r[\"_measurement\"] == \"Joints_position_3\" or r[\"_measurement\"] == \"Joints_position_4\" or r[\"_measurement\"] == \"Joints_position_5\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Joints Temperature",
   "type": "timeseries",
   "description": "Visualizations of Joints Temperature of Universal Robots",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"UR10e\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Joints_temperature0\" or r[\"_measurement\"] == \"Joints_temperature1\" or r[\"_measurement\"] == \"Joints_temperature2\" or r[\"_measurement\"] == \"Joints_temperature3\" or r[\"_measurement\"] == \"Joints_temperature4\" or r[\"_measurement\"] == \"Joints_temperature5\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Joints Current",
   "type": "timeseries",
   "description": "Visualization of Current in Joints",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"UR10e\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Joints_current0\" or r[\"_measurement\"] == \"Joints_current1\" or r[\"_measurement\"] == \"Joints_current2\" or r[\"_measurement\"] == \"Joints_current3\" or r[\"_measurement\"] == \"Joints_current4\" or r[\"_measurement\"] == \"Joints_current5\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Scalar Force",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "forceN" } },
   "targets": [
    {
     "query": "from(bucket: \"UR10e\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TCP_force_scalar\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}