apiVersion: 1
datasources:
  - name: InfluxDB_UR10e
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux  
      organization: "CTC"  
      bucket: "UR10e"  
    secureJsonData:
      token: "testtoken"  
